language: ruby
rvm:
- 2.2.4
deploy:
  provider: heroku
  api_key:
    secure: eGvWm+gd3JtF7xLb+sgaHT/kXXcwV/8y31FB/y/Y7XhXXjn/F0UATEoqTUuTLlrQdfPTPkG7TfGc7oQaY+FfOdGCJXGwR1DZ7PwX2YMRi3HtT1nCUqOYpE1t80UIRAckwQxj+gADuMih/kDnUwSRslBY3cJFxrcuh/ERK6gXw6BfHXIoOEq+D18VgJt9rCCJE67sg7F9ZWGIrnzM70Lb8uHI9LMYylsKlKnreHli7JszDdODator9j7tg/HzBDEBIRepcOx5feXBcYwSjpglAiFK1WmFU6wRuavJYYPp00/fOKCKCHmeQnhpts9O/59/HIKlbLgkXS1Se6hS0DwUjk6NsrBn0EzJ9jsw0j6W2mfgMEc6wtl8ZSdEE8BTSn7xm3K0CuS0PIPCSbuPRNjDrSu937taH70If4r9YInuoTbtnieqY8W6hX0nWoxg43G1rjiwwgx0QIeeN3w+jSAakokYNGkrFiiYlYU3y8jHXwT6xxMr7TF9fjqEXaQIeXHz/sa8+ylTtTtctOnO5/GpBVUVqszgDKeZa20aWtyFt00iU9mjCP2mXRiR5WCEgzbAbtfCNqaA7SYnFD5kyrDMlsY+D+zDJ6d3ssQyiIBhZ0oyfU3AcUa8lDz1jgF0npt2b6KcaUnUMCghwinuoEKaBdSyi66lbMKshyW/0KBJcX4=
  app: glacial-caverns-69838
  on:
    repo: quentinpmf/projet
